### PR TITLE
adding rule clippy::indexing_slicing to wannabe land blocking yml

### PR DESCRIPTION
**Pull request by xvschneider**
Adding indexing slicing clippy lint to Mirai bot
more info here https://rust-lang.github.io/rust-clippy/master/#indexing_slicing

### CODE REVIEW

**Comment by xvschneider** [comment]
cc: @mimoo

**Comment by mimoo** [comment]
awesome thx : )

**Comment by mimoo** [comment]
perhaps it'd be a good idea to remove these rules from the #clippy bot : o

**Comment by xvschneider** [comment]
> ese rules from the #clippy bot : o

so that it doesn't double comment?

**Comment by mimoo** [comment]
yeah, or if it double comments that it doesn't contain redundant information

**Pull request merged**
